// The /docs page — a long-form, editorial explanation of Umbra: the problem it
// solves, how the privacy works under the hood, the on-chain design, and how to
// install the Chrome extension. Rendered inside the SPA so it inherits the DA.
const REL = "https://github.com/abaresks24/umbra/releases/latest/download/umbra-extension.zip";
const REPO = "https://github.com/abaresks24/umbra";

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

export function docsView(cfg) {
  const pool = cfg?.poolId ? esc(cfg.poolId) : "—";
  const assets = (cfg?.assets || []).map((a) => esc(a.symbol)).join(" · ") || "USDC · WETH";
  return `<div class="screen doc">
  <header class="bar">
    <div class="brand"><img class="brand-logo" src="/logo.png" alt="" aria-hidden="true"/>Umbra</div>
    <button class="btn ghost sm" id="doc-back">← Back</button>
  </header>

  <article class="doc-body">
    <p class="doc-kicker">Documentation</p>
    <h1 class="doc-title">Privacy is a right, not a feature.</h1>
    <p class="doc-lede">Umbra is a privacy wallet for the Stellar network. Balances, amounts and
      counterparties stay hidden on-chain — yet every payment carries a cryptographic proof that it is
      valid, and a sealed disclosure that a designated auditor (and only that auditor) can open. Privacy
      without impunity.</p>

    <nav class="doc-toc">
      <a href="#what">The problem</a>
      <a href="#model">How privacy works</a>
      <a href="#zk">The zero-knowledge proof</a>
      <a href="#audit">Enforced auditability</a>
      <a href="#chain">On Stellar / Soroban</a>
      <a href="#flow">A payment, end to end</a>
      <a href="#multi">Multiple assets</a>
      <a href="#stack">Tech stack</a>
      <a href="#install">Install the extension</a>
    </nav>

    <section id="what">
      <h2>The problem</h2>
      <p>A public blockchain is a permanent, searchable ledger. Send someone a stablecoin and you have
        also told the world your balance, your salary, your suppliers, your donations. For individuals it
        is surveillance; for businesses it leaks margins and counterparties. The usual answer — a fully
        anonymous mixer — trades one extreme for another: it becomes a haven for illicit funds and gets
        sanctioned.</p>
      <p>Umbra takes the middle path that regulators and users can both live with:
        <strong>confidential to the public, accountable to an auditor.</strong></p>
    </section>

    <section id="model">
      <h2>How privacy works — the shielded UTXO model</h2>
      <p>Instead of public account balances, Umbra holds value in <em>notes</em> (a shielded UTXO model,
        in the Tornado-Nova family). A note is a secret bundle:</p>
      <pre class="doc-code">note = { amount, assetId, owner_pubkey, blinding }</pre>
      <p>What the chain actually stores is only a <em>commitment</em> — a Poseidon hash of that bundle —
        appended as a leaf to an on-chain Merkle tree:</p>
      <pre class="doc-code">commitment = Poseidon(amount, assetId, owner_pubkey, blinding)</pre>
      <p>The commitment reveals nothing: the <code>blinding</code> randomizes it, so two notes for the
        same amount look completely different. To spend a note you publish its <em>nullifier</em>, a
        deterministic tag derived from the note and your spend key. The contract records spent
        nullifiers, so a note can never be spent twice — but because the nullifier is unlinkable to the
        commitment, no observer can tell <em>which</em> note was consumed.</p>
      <ul>
        <li><strong>Commitments</strong> prove a note exists, without revealing it.</li>
        <li><strong>Nullifiers</strong> prevent double-spends, without revealing which note was spent.</li>
        <li><strong>View keys</strong> let a recipient (via an encrypted memo) discover their own incoming
          notes by scanning the chain — only they can decrypt them.</li>
      </ul>
    </section>

    <section id="zk">
      <h2>The zero-knowledge proof</h2>
      <p>Every transaction carries a <strong>Groth16 zk-SNARK</strong>, generated by a circuit written in
        Circom 2 over the BN254 curve. The proof convinces the contract — without revealing any secret —
        that:</p>
      <ul>
        <li>every input note really exists in the Merkle tree (a valid Merkle membership proof);</li>
        <li>the spender owns those inputs (knows the spend key behind each <code>owner_pubkey</code>);</li>
        <li>inputs and outputs <strong>balance</strong>: nothing is created or destroyed, per asset;</li>
        <li>the nullifiers and output commitments are computed correctly.</li>
      </ul>
      <p>The hash inside the circuit is <strong>Poseidon</strong> (from circomlib), chosen because it is
        cheap in a SNARK <em>and</em> available as a native Soroban host function — so the same hash is
        computed identically off-chain and on-chain. Crucially, <strong>proving runs on your device</strong>
        (snarkjs over the circuit WASM + proving key, bundled into the app and the extension). The witness —
        your amounts, keys and blindings — never leaves your machine. Only the ~200-byte proof and the
        encrypted outputs are submitted.</p>
    </section>

    <section id="audit">
      <h2>Enforced auditability — the part that makes it deployable</h2>
      <p>An anonymous mixer is illegal in most places because it has no off-ramp for law enforcement.
        Umbra's distinctive feature is that <strong>disclosure to a designated auditor is enforced by the
        proof itself</strong>, not bolted on afterwards.</p>
      <p>For every output note, the sender encrypts the note's contents to the auditor's public key using
        <strong>Baby Jubjub ElGamal</strong>, and the circuit verifies — as one of its constraints — that
        this ciphertext is well-formed and decrypts to the very same note being committed. A transaction
        with a missing or malformed auditor ciphertext simply <em>cannot produce a valid proof</em>, so the
        contract rejects it. The auditor (and nobody else) holds the private key that opens these
        ciphertexts and can reconstruct any note's amount and owner. Everyone else sees only opaque
        commitments. This is the line between <em>privacy</em> and <em>opacity</em>.</p>
    </section>

    <section id="chain">
      <h2>On Stellar / Soroban</h2>
      <p>The pool is a Soroban smart contract (Rust). It maintains:</p>
      <ul>
        <li>an <strong>incremental Merkle tree</strong> (depth 16) of note commitments, with a
          root-history ring buffer so proofs against a recent root stay valid;</li>
        <li>a <strong>nullifier set</strong> of everything ever spent;</li>
        <li>a Groth16 <strong>verifier</strong> that runs on Soroban's <em>native BN254 host functions</em>
          — pairing checks and field arithmetic at native speed rather than in interpreted WASM.</li>
      </ul>
      <p>Each successful transaction emits events (new commitments, nullifiers, and the sealed auditor
        ciphertexts) so wallets and the auditor can reconstruct state by scanning, with no central
        indexer.</p>
      <p class="doc-meta">Live testnet pool: <code>${pool}</code> · assets ${assets}</p>
    </section>

    <section id="flow">
      <h2>A payment, end to end</h2>
      <h3>Deposit (shield)</h3>
      <p>You move public tokens into the pool from your own Stellar wallet. The deposit is
        <strong>self-custodial</strong>: it is signed and paid by you via <strong>Freighter</strong> — the
        relayer never touches your funds. A new note (your shielded balance) is created.</p>
      <h3>Send (private transfer)</h3>
      <p>Your device builds the proof locally, encrypts the new note to the recipient's view key and to the
        auditor, and hands the proof + ciphertexts to a <strong>relayer</strong> that submits the
        transaction and pays the network fee. Because the relayer only relays a finished proof, it learns
        nothing about amounts or parties. On-chain, observers see an opaque state update.</p>
      <h3>Withdraw (unshield)</h3>
      <p>Value returns to the public light: the proof authorizes paying out to a normal Stellar address,
        burning the corresponding shielded notes.</p>
    </section>

    <section id="multi">
      <h2>Multiple assets</h2>
      <p>Notes carry an <code>assetId</code>, and the circuit enforces balance <em>per asset</em>, so a
        single shielded pool holds several tokens (e.g. USDC and WETH) without mixing their value. The
        wallet's home shows your <strong>total portfolio value</strong>, which you can denominate in either
        token via the toggle, with the per-token holdings listed underneath.</p>
    </section>

    <section id="stack">
      <h2>Tech stack</h2>
      <ul>
        <li><strong>Circuits:</strong> Circom 2 + Groth16 (snarkjs), BN254, Poseidon (circomlib),
          Baby Jubjub ElGamal for auditor disclosure.</li>
        <li><strong>Contract:</strong> Rust / Soroban, native BN254 host functions, incremental Merkle
          tree, nullifier set, root-history ring buffer.</li>
        <li><strong>Client:</strong> Vite SPA, in-browser proving, <code>@stellar/stellar-sdk</code>,
          Freighter for self-custodial deposits; a serverless relayer for private transfers/withdrawals.</li>
        <li><strong>Extension:</strong> Manifest V3 popup, same client-side proving (single-threaded to
          stay inside the extension CSP).</li>
      </ul>
      <p>Source: <a href="${REPO}" target="_blank" rel="noopener">${REPO.replace("https://", "")}</a></p>
    </section>

    <section id="install" class="doc-install">
      <h2>Install the Chrome extension</h2>
      <p>The extension is the full wallet in a browser popup. Because it isn't on the Chrome Web Store yet,
        you load it once in Developer mode — about 30 seconds.</p>
      <ol class="doc-steps">
        <li><strong>Download</strong> the package:
          <a class="btn primary sm dl" href="${REL}">Download umbra-extension.zip ↧</a></li>
        <li><strong>Unzip it.</strong> Double-click the downloaded file. Keep the resulting folder
          somewhere stable (e.g. <code>Documents/umbra-extension</code>) — Chrome reads it in place, so
          don't delete or move it afterwards.</li>
        <li>Open <code>chrome://extensions</code> in your browser.</li>
        <li>Turn on <strong>Developer mode</strong> (toggle, top-right).</li>
        <li>Click <strong>Load unpacked</strong> and select the unzipped folder.</li>
        <li>Click the puzzle icon 🧩 in the toolbar and <strong>pin</strong> Umbra. Click it to open the
          wallet.</li>
      </ol>
      <p class="doc-note"><strong>Note on deposits in the extension.</strong> Freighter can't be reached
        from inside an extension popup, so the <em>Deposit</em> button opens the web app to sign with
        Freighter; your new balance then appears in the popup automatically. Everything else — send,
        withdraw, receive, balances — runs in the popup.</p>
    </section>

    <footer class="doc-foot">
      <span>Umbra · privacy on Stellar</span>
      <button class="link sm" id="doc-back-2">↑ Back to the wallet</button>
    </footer>
  </article>
</div>`;
}
